### ISSUE TITLE
approx1 off_grid Error

### ISSUE THREAD

**Issue by ajflood** [arrayfire/arrayfire-python#118]
When working with the approx1 function I found an error in singal.py.  I found that the off_grid format should be float not double.  I have tested it on my machine and it now works as expected.

Here is the previous code:
`safe_call(backend.get().af_approx1(c_pointer(output.arr), signal.arr, pos0.arr,method.value, c_double_t(off_grid)))`

Which I changed to fix the problem:
`safe_call(backend.get().af_approx1(c_pointer(output.arr),` signal.arr, pos0.arr,method.value, `c_float_t(off_grid)))`

Sorry if this is not proper procedure for fixing bugs, this is my first time reporting bugs using github.

**Comment by pavanky** [comment]
@ajflood The procedure to send in a bug fix can be found here: https://github.com/arrayfire/arrayfire/wiki/Contribute-code-using-github


Please use `arrayfire-python` instead of `arrayfire` wherever required. Let me know if you have any questions regarding the process. 

Welcome to the world of open source contributors!
