### ISSUE TITLE
dims not working on 32 bit versions

### ISSUE THREAD

**Issue by pavanky** [arrayfire/arrayfire-python#72]
Relevant info: https://github.com/arrayfire/arrayfire/issues/1365

**Comment by colbyshores** [comment]
I took a shot in the dark here and it appears the issue resides in ct.c_longlong as it is a 64 bit value.  I changed util.py's dim4 method on line 15 to 


```
def dim4(d0=1, d1=1, d2=1, d3=1):
    c_dim4 = ct.c_long * 4      '''32 bit value
    out = c_dim4(1, 1, 1, 1)

    for i, dim in enumerate((d0, d1, d2, d3)):
        if (dim is not None): out[i] = dim

    return out
```

from

```
def dim4(d0=1, d1=1, d2=1, d3=1):
    c_dim4 = ct.c_longlong * 4  #64bit value
    out = c_dim4(1, 1, 1, 1)

    for i, dim in enumerate((d0, d1, d2, d3)):
        if (dim is not None): out[i] = dim

    return out
```

and then the hello world program executed properly.

Im going to find and replace all instances with a 32bit long in the code if the only impact will be performance and memory allocation due to the 32bit map.

**Comment by pavanky** [comment]
@colbyshores I knew what the issue was when you reported the bug. But simply changing longlong to long will break on windows. I need to fix it in a more proper manner.

**Comment by ghisvail** [comment]
Since in AF, `dim4` is defined as an aggregate of four `dim_t` and `dim_t` is arch-dependent then the proper fix may be to define a `c_dim_t` in the Python API and use it in the utility function?

**Comment by pavanky** [comment]
@ghisvail That's the plan. I am just a bit surprised that I did not do that yet.

**Comment by ghisvail** [comment]
Let me know when you have a fix committed and I'll apply it to the packaging. Unless you plan to make a new release soon with the fix.

**Comment by pavanky** [comment]
This is fixed in master.

**Comment by pavanky** [comment]
@colbyshores This fix is now both in devel and master. Can you check if this works for you ?

**Comment by colbyshores** [comment]
Looks great on the dims!  Many examples work now.  The examples that segfault are those in graphics: cos, sin, maxof, constant.  Should I create a new bug report for these?

**Comment by pavanky** [comment]
Hmm I ran the tests and all of them passed. Forgot to run the tests though..

**Comment by pavanky** [comment]
@colbyshores looks like the graphics examples themselves are a bit buggy. Is there any stand alone code that will reproduce the segfaults ? Can you also print the output of `af.info()` ?

**Comment by colbyshores** [comment]
You're right, it looks like all the methods are working except the close() method for window handling at a glance, though since you mentioned the buggy graphics I am sure you already aware of it.  



ArrayFire v3.3.1 (CUDA, 32-bit Linux, build f53efc3)
Platform: CUDA Toolkit 6.5, Driver: CUDA Driver Version: 6050
[0] GK20A, 4018 MB, CUDA Compute 3.2

```
import arrayfire as af
af.info()
win = af.Window(800,800,"window")
a = win.close() #close method is buggy, segfauts here
print(a)
exit(0)
```

**Comment by pavanky** [comment]
@colbyshores I'll look into fixing this. Thanks for taking time to reproduce the issues.

**Comment by colbyshores** [comment]
No problem, thanks for your help too.
